version: "3.8"

networks:
  airline:
    driver: bridge

services:
  eureka:
    container_name: flightmanagement-eureka
    build: ./eureka-service/eureka-service
    hostname: eureka-service
    networks:
      - airline
    environment:
      SERVER_PORT: 8761

  auth:
    depends_on:
      - eureka
      - db
    container_name: flightmanagement-auth
    build: ./authourization-server
    hostname: auth-service
    networks:
      - airline
    environment:
      SERVER_PORT: 8771
      EUREKA_PORT: 8761
      EUREKA_HOST: eureka-service
      DB_SERVER: mysql
      AUTH_SERVER_NAME: auth-service
    command: ["/authourization-server/docker-entrypoint.sh"]

  airline:
    depends_on:
      - eureka
      - db
    container_name: flightmanagement-airlinebookingservice
    build: ./airline-booking-service/airline-booking-service
    hostname: airline-service
    networks:
      - airline
    environment:
      SERVER_PORT: 8089
      EUREKA_PORT: 8761
      EUREKA_HOST: eureka-service
      DB_SERVER: mysql
      AUTH_SERVER_HOST: auth-service
      AUTH_PORT: 8771
    command: ["/airline-booking-service/docker-entrypoint.sh"]

  gateway:
    depends_on:
      - eureka
      - auth
    container_name: flightmanagement-gateway
    build: ./gateway
    networks:
      - airline
    ports:
      - 8443:8443
    environment:
      SERVER_PORT: 8443
      EUREKA_PORT: 8761
      EUREKA_HOST: eureka-service
      AUTH_SERVER_HOST: auth-service
      AUTH_PORT: 8771
  db:
    image: mysql:latest
    container_name: mysql_flight
    hostname: mysql
    networks:
      - airline
    ports:
      - 3306:3306
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - USER=root
      - PASSWORD=''