version: "3.7"

networks:
  airline:
    driver: bridge

services:
  client:
    container_name: client
    image: 'node:latest'
    volumes:
      - ./client:/app
    networks:
      - airline
    ports:
      - '3000:3000'
    entrypoint: /bin/sh
    command: -c "sleep 5 && cd /app/ && npm ci && npm run build && npm run start"

  #admin

  user:
    container_name: user
    image: openjdk:17
    networks:
      - airline
    ports:
      - 8081:8081
    volumes:
      - ./user:/usr/src/user
    entrypoint: /bin/bash
    command: -c "/usr/src/user/mvnw clean package -B && java --jar user-0.0.1-0.0.1-SNAPSHOT.jar --spring.config.location=file:application.yml"

#  mysql:
#    image: mysql:latest
#    container_name: mysql
#    networks:
#      - airline
#    ports:
#      - 3306:3306
#    environment:
#      - USER=root
#      - PASSWORD=''
#      - DB='fms'

