server.forward-headers-strategy: framework

spring.application.name: auth-server

app:
  eureka-username: u
  eureka-password: p
  eureka-server: ${EUREKA_HOST}
  eureka-port: ${EUREKA_PORT}
  db-server: ${DB_SERVER}
  host-name: ${AUTH_SERVER_NAME}
  security:
    #change to local URL
    redirect-url: http://localhost:4000

eureka:
  client:
    serviceUrl:
      defaultZone: "http://${app.eureka-username}:${app.eureka-password}@${app.eureka-server}:${app.eureka-port}/eureka/"
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5

management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"

logging:
  level:
    root: INFO

spring:
  datasource:
    url: jdbc:mysql://${app.db-server}:3306/fmsAuth?createDatabaseIfNotExist=true
    username: root
    password:
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update
    show_sql: true
    database: mysql
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
      hibernate.format_sql: true
  data:
    jpa:
      repositories:
        enabled: true
  sql:
    init:
      mode: always
---
#spring.config.activate.on-profile: docker
